// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_url_handler.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostAPIShortenService is a mock of PostAPIShortenService interface.
type MockPostAPIShortenService struct {
	ctrl     *gomock.Controller
	recorder *MockPostAPIShortenServiceMockRecorder
	isgomock struct{}
}

// MockPostAPIShortenServiceMockRecorder is the mock recorder for MockPostAPIShortenService.
type MockPostAPIShortenServiceMockRecorder struct {
	mock *MockPostAPIShortenService
}

// NewMockPostAPIShortenService creates a new mock instance.
func NewMockPostAPIShortenService(ctrl *gomock.Controller) *MockPostAPIShortenService {
	mock := &MockPostAPIShortenService{ctrl: ctrl}
	mock.recorder = &MockPostAPIShortenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostAPIShortenService) EXPECT() *MockPostAPIShortenServiceMockRecorder {
	return m.recorder
}

// Shorten mocks base method.
func (m *MockPostAPIShortenService) Shorten(fullURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", fullURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockPostAPIShortenServiceMockRecorder) Shorten(fullURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockPostAPIShortenService)(nil).Shorten), fullURL)
}
