// Code generated by MockGen. DO NOT EDIT.
// Source: url_storage.go
//
// Generated by this command:
//
//	mockgen -source=url_storage.go -destination=mocks/mock_url_storage.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUrlStorage is a mock of UrlStorage interface.
type MockUrlStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUrlStorageMockRecorder
	isgomock struct{}
}

// MockUrlStorageMockRecorder is the mock recorder for MockUrlStorage.
type MockUrlStorageMockRecorder struct {
	mock *MockUrlStorage
}

// NewMockUrlStorage creates a new mock instance.
func NewMockUrlStorage(ctrl *gomock.Controller) *MockUrlStorage {
	mock := &MockUrlStorage{ctrl: ctrl}
	mock.recorder = &MockUrlStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUrlStorage) EXPECT() *MockUrlStorageMockRecorder {
	return m.recorder
}

// GetFullUrl mocks base method.
func (m *MockUrlStorage) GetFullUrl(shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFullUrl", shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFullUrl indicates an expected call of GetFullUrl.
func (mr *MockUrlStorageMockRecorder) GetFullUrl(shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFullUrl", reflect.TypeOf((*MockUrlStorage)(nil).GetFullUrl), shortURL)
}

// SetShortUrl mocks base method.
func (m *MockUrlStorage) SetShortUrl(shortURL, fullURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetShortUrl", shortURL, fullURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetShortUrl indicates an expected call of SetShortUrl.
func (mr *MockUrlStorageMockRecorder) SetShortUrl(shortURL, fullURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetShortUrl", reflect.TypeOf((*MockUrlStorage)(nil).SetShortUrl), shortURL, fullURL)
}
