// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_url_handler.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetFullURLService is a mock of GetFullURLService interface.
type MockGetFullURLService struct {
	ctrl     *gomock.Controller
	recorder *MockGetFullURLServiceMockRecorder
	isgomock struct{}
}

// MockGetFullURLServiceMockRecorder is the mock recorder for MockGetFullURLService.
type MockGetFullURLServiceMockRecorder struct {
	mock *MockGetFullURLService
}

// NewMockGetFullURLService creates a new mock instance.
func NewMockGetFullURLService(ctrl *gomock.Controller) *MockGetFullURLService {
	mock := &MockGetFullURLService{ctrl: ctrl}
	mock.recorder = &MockGetFullURLServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetFullURLService) EXPECT() *MockGetFullURLServiceMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockGetFullURLService) Resolve(shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockGetFullURLServiceMockRecorder) Resolve(shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockGetFullURLService)(nil).Resolve), shortURL)
}
