// Code generated by MockGen. DO NOT EDIT.
// Source: internal/authentication/parser.go
//
// Generated by this command:
//
//	mockgen -source=internal/authentication/parser.go -destination=internal/authentication/mocks/mock_parser.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockUserIDParser is a mock of UserIDParser interface.
type MockUserIDParser struct {
	ctrl     *gomock.Controller
	recorder *MockUserIDParserMockRecorder
	isgomock struct{}
}

// MockUserIDParserMockRecorder is the mock recorder for MockUserIDParser.
type MockUserIDParserMockRecorder struct {
	mock *MockUserIDParser
}

// NewMockUserIDParser creates a new mock instance.
func NewMockUserIDParser(ctrl *gomock.Controller) *MockUserIDParser {
	mock := &MockUserIDParser{ctrl: ctrl}
	mock.recorder = &MockUserIDParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserIDParser) EXPECT() *MockUserIDParserMockRecorder {
	return m.recorder
}

// GetUserID mocks base method.
func (m *MockUserIDParser) GetUserID(tokenString string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserID", tokenString)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserID indicates an expected call of GetUserID.
func (mr *MockUserIDParserMockRecorder) GetUserID(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserID", reflect.TypeOf((*MockUserIDParser)(nil).GetUserID), tokenString)
}
