// Code generated by MockGen. DO NOT EDIT.
// Source: internal/authentication/jwt.go
//
// Generated by this command:
//
//	mockgen -source=internal/authentication/jwt.go -destination=internal/authentication/mocks/mock_jwt.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenBuilder is a mock of TokenBuilder interface.
type MockTokenBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockTokenBuilderMockRecorder
	isgomock struct{}
}

// MockTokenBuilderMockRecorder is the mock recorder for MockTokenBuilder.
type MockTokenBuilderMockRecorder struct {
	mock *MockTokenBuilder
}

// NewMockTokenBuilder creates a new mock instance.
func NewMockTokenBuilder(ctrl *gomock.Controller) *MockTokenBuilder {
	mock := &MockTokenBuilder{ctrl: ctrl}
	mock.recorder = &MockTokenBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenBuilder) EXPECT() *MockTokenBuilderMockRecorder {
	return m.recorder
}

// BuildJWTString mocks base method.
func (m *MockTokenBuilder) BuildJWTString(userID string, tokenExp time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuildJWTString", userID, tokenExp)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BuildJWTString indicates an expected call of BuildJWTString.
func (mr *MockTokenBuilderMockRecorder) BuildJWTString(userID, tokenExp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuildJWTString", reflect.TypeOf((*MockTokenBuilder)(nil).BuildJWTString), userID, tokenExp)
}
