// Code generated by MockGen. DO NOT EDIT.
// Source: url_storage.go
//
// Generated by this command:
//
//	mockgen -source=url_storage.go -destination=mocks/mock_url_storage.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CimaCha/go-url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLStorage is a mock of URLStorage interface.
type MockURLStorage struct {
	ctrl     *gomock.Controller
	recorder *MockURLStorageMockRecorder
	isgomock struct{}
}

// MockURLStorageMockRecorder is the mock recorder for MockURLStorage.
type MockURLStorageMockRecorder struct {
	mock *MockURLStorage
}

// NewMockURLStorage creates a new mock instance.
func NewMockURLStorage(ctrl *gomock.Controller) *MockURLStorage {
	mock := &MockURLStorage{ctrl: ctrl}
	mock.recorder = &MockURLStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLStorage) EXPECT() *MockURLStorageMockRecorder {
	return m.recorder
}

// FindFullURL mocks base method.
func (m *MockURLStorage) FindFullURL(ctx context.Context, shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFullURL", ctx, shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFullURL indicates an expected call of FindFullURL.
func (mr *MockURLStorageMockRecorder) FindFullURL(ctx, shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFullURL", reflect.TypeOf((*MockURLStorage)(nil).FindFullURL), ctx, shortURL)
}

// GetUserURLs mocks base method.
func (m *MockURLStorage) GetUserURLs(ctx context.Context, userId string) ([]*model.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userId)
	ret0, _ := ret[0].([]*model.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockURLStorageMockRecorder) GetUserURLs(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockURLStorage)(nil).GetUserURLs), ctx, userId)
}

// SaveShortURL mocks base method.
func (m *MockURLStorage) SaveShortURL(ctx context.Context, shortURL, fullURL, userId string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortURL", ctx, shortURL, fullURL, userId)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveShortURL indicates an expected call of SaveShortURL.
func (mr *MockURLStorageMockRecorder) SaveShortURL(ctx, shortURL, fullURL, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortURL", reflect.TypeOf((*MockURLStorage)(nil).SaveShortURL), ctx, shortURL, fullURL, userId)
}

// SaveShortUrlBatch mocks base method.
func (m *MockURLStorage) SaveShortUrlBatch(ctx context.Context, URLRecords []*model.URLRecord, userId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveShortUrlBatch", ctx, URLRecords, userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveShortUrlBatch indicates an expected call of SaveShortUrlBatch.
func (mr *MockURLStorageMockRecorder) SaveShortUrlBatch(ctx, URLRecords, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveShortUrlBatch", reflect.TypeOf((*MockURLStorage)(nil).SaveShortUrlBatch), ctx, URLRecords, userId)
}
