// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/delete-url-batch/handler.go
//
// Generated by this command:
//
//	mockgen -source=internal/handler/delete-url-batch/handler.go -destination=internal/handler/delete-url-batch/mocks/mock_deleter.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"
	time "time"

	service "github.com/CimaCha/go-url-shortener/internal/service"
	gomock "go.uber.org/mock/gomock"
)

// MockDeleter is a mock of Deleter interface.
type MockDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockDeleterMockRecorder
	isgomock struct{}
}

// MockDeleterMockRecorder is the mock recorder for MockDeleter.
type MockDeleterMockRecorder struct {
	mock *MockDeleter
}

// NewMockDeleter creates a new mock instance.
func NewMockDeleter(ctrl *gomock.Controller) *MockDeleter {
	mock := &MockDeleter{ctrl: ctrl}
	mock.recorder = &MockDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleter) EXPECT() *MockDeleterMockRecorder {
	return m.recorder
}

// ProcessDeleteTasks mocks base method.
func (m *MockDeleter) ProcessDeleteTasks(onError func(error), batchSize int, timeout time.Duration, inputs ...<-chan service.DeleteTask) {
	m.ctrl.T.Helper()
	varargs := []any{onError, batchSize, timeout}
	for _, a := range inputs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "ProcessDeleteTasks", varargs...)
}

// ProcessDeleteTasks indicates an expected call of ProcessDeleteTasks.
func (mr *MockDeleterMockRecorder) ProcessDeleteTasks(onError, batchSize, timeout any, inputs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{onError, batchSize, timeout}, inputs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessDeleteTasks", reflect.TypeOf((*MockDeleter)(nil).ProcessDeleteTasks), varargs...)
}
