// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_url_handler.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostShortenService is a mock of PostShortenService interface.
type MockPostShortenService struct {
	ctrl     *gomock.Controller
	recorder *MockPostShortenServiceMockRecorder
	isgomock struct{}
}

// MockPostShortenServiceMockRecorder is the mock recorder for MockPostShortenService.
type MockPostShortenServiceMockRecorder struct {
	mock *MockPostShortenService
}

// NewMockPostShortenService creates a new mock instance.
func NewMockPostShortenService(ctrl *gomock.Controller) *MockPostShortenService {
	mock := &MockPostShortenService{ctrl: ctrl}
	mock.recorder = &MockPostShortenServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostShortenService) EXPECT() *MockPostShortenServiceMockRecorder {
	return m.recorder
}

// Shorten mocks base method.
func (m *MockPostShortenService) Shorten(fullURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shorten", fullURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Shorten indicates an expected call of Shorten.
func (mr *MockPostShortenServiceMockRecorder) Shorten(fullURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shorten", reflect.TypeOf((*MockPostShortenService)(nil).Shorten), fullURL)
}
