// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_pinger.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockGetPingService is a mock of GetPingService interface.
type MockGetPingService struct {
	ctrl     *gomock.Controller
	recorder *MockGetPingServiceMockRecorder
	isgomock struct{}
}

// MockGetPingServiceMockRecorder is the mock recorder for MockGetPingService.
type MockGetPingServiceMockRecorder struct {
	mock *MockGetPingService
}

// NewMockGetPingService creates a new mock instance.
func NewMockGetPingService(ctrl *gomock.Controller) *MockGetPingService {
	mock := &MockGetPingService{ctrl: ctrl}
	mock.recorder = &MockGetPingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetPingService) EXPECT() *MockGetPingServiceMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockGetPingService) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockGetPingServiceMockRecorder) Ping(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockGetPingService)(nil).Ping), arg0)
}
