// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_user_urls_getter.gen.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	model "github.com/CimaCha/go-url-shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserURLsGetter is a mock of UserURLsGetter interface.
type MockUserURLsGetter struct {
	ctrl     *gomock.Controller
	recorder *MockUserURLsGetterMockRecorder
	isgomock struct{}
}

// MockUserURLsGetterMockRecorder is the mock recorder for MockUserURLsGetter.
type MockUserURLsGetterMockRecorder struct {
	mock *MockUserURLsGetter
}

// NewMockUserURLsGetter creates a new mock instance.
func NewMockUserURLsGetter(ctrl *gomock.Controller) *MockUserURLsGetter {
	mock := &MockUserURLsGetter{ctrl: ctrl}
	mock.recorder = &MockUserURLsGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserURLsGetter) EXPECT() *MockUserURLsGetterMockRecorder {
	return m.recorder
}

// GetUserURLs mocks base method.
func (m *MockUserURLsGetter) GetUserURLs(ctx context.Context, userId string) ([]*model.UserRecord, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", ctx, userId)
	ret0, _ := ret[0].([]*model.UserRecord)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockUserURLsGetterMockRecorder) GetUserURLs(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockUserURLsGetter)(nil).GetUserURLs), ctx, userId)
}
